### ISSUE TITLE
Data attributes

### ISSUE THREAD

**Issue by intrnl** [joe27g/EnhancedDiscord#11]
Data attributes and classes in messages, members, guilds etc. for plugins/themes to mess with.   
These data attributes examples are taken from BDv2

![image](https://user-images.githubusercontent.com/20620901/38492773-3b007c1c-3c1a-11e8-904f-c6b7f43ed52c.png)
![image](https://user-images.githubusercontent.com/20620901/38492839-66bbc690-3c1a-11e8-9527-40ee359785d4.png)
![image](https://user-images.githubusercontent.com/20620901/38492866-79eeaee4-3c1a-11e8-9262-548c46921e18.png)

**Comment by CAC27** [comment]
I can see using this for some tinkering, but if it's included, it will be added as an optional plugin to avoid wasting performance on it when not needed.

**Comment by joe27g** [comment]
This issue is very stale, may as well close it.
