### ISSUE TITLE
Limit to CSS

### ISSUE THREAD

**Issue by s01b01** [joe27g/EnhancedDiscord#114]
While trying to use the "Add new plugin or theme" option, and selecting my own CSS theme, nothing happens. So I tried installing a theme, going to the folder for the plugin, and replacing the CSS in there with my own, which was similar enough in size, but when I reloaded discord it seemed that the injector crashed all together when looking in settings. Testing with only parts of my theme, it seems that it works up until a certain number of lines, regardless of the contents of said lines.

**Comment by rauenzi** [comment]
Can you be more specific with what you mean by
> Add new plugin or theme option

**Comment by s01b01** [comment]
> Can you be more specific with what you mean by
> 
> > Add new plugin or theme option

In settings there's a button that I assume is to upload the code for a theme or plugin, and upon clicking I can select a .css file from my computer. The issue there is once I select it, nothing happens, just closes when I hit "open" and doesn't change the CSS or add anything.

**Comment by rauenzi** [comment]
Are you referring to this? https://i.imgur.com/6gUoJql.png

**Comment by s01b01** [comment]
> Are you referring to this? https://i.imgur.com/6gUoJql.png

Strange, I actually don't see anything like that in my settings. For me it's a button where I then open a directory. https://imgur.com/a/1gPSG5H

**Comment by intrnl** [comment]
You seem to be using DiscordInjections not EnhancedDiscord

**Comment by s01b01** [comment]
> You seem to be using DiscordInjections not EnhancedDiscord

Oh I'm very sorry, the file was in discord's config file so couldn't really tell, every update my old injector breaks and I have to try out another one and I must have made a mistake across the days. Thank you for clearing that up.

**Comment by rauenzi** [comment]
Closing as this isn't about ED.
