### ISSUE TITLE
Crash upon trying to open a server

### ISSUE THREAD

**Issue by s01b01** [joe27g/EnhancedDiscord#115]
I'm on Linux, using only for CSS. At some point a few days ago I had closed discord and when I reopened it the CSS had loaded in fine and I could see DM's, friend's list, ETC. But upon trying to open a server, discord crashes, giving me this page https://imgur.com/a/Vm4EPkl. I confirmed this only happens after adding the lines to the top of the inject.js file.

**Comment by MasicoreLord** [comment]
@s01b01 If this occurred on the beta, please try switching to stable, as there was a crash issue that was only worked around there.

**Comment by s01b01** [comment]
> @s01b01 If this occurred on the beta, please try switching to stable, as there was a crash issue that was only worked around there.

Sorry, not sure what you're referring to. Not aware of a stable or beta of this.

**Comment by MasicoreLord** [comment]
@s01b01 If you aren't sure, it's likely stable, as beta would be installed only if you select the opt into beta option in the installer.

**Comment by MasicoreLord** [comment]
If you haven't already try updating EnhancedDiscord

**Comment by s01b01** [comment]
> If you haven't already try updating EnhancedDiscord

Yeh, I thought I did but turns out I didn't, just tried a minute ago. Thank you very much, sorry about that.

**Comment by MasicoreLord** [comment]
You are welcome, next make sure things are up to date before reporting a bug, as otherwise it might have already been patched.
