### ISSUE TITLE
Discord freezes when a new message arrives and i'm tabbed not in Discord

### ISSUE THREAD

**Issue by alx365** [joe27g/EnhancedDiscord#117]
title.  (Sry, I am lazy)
I am on Linux manjaro kde plasma.
Any ideas?

**Comment by YouKnowBlom** [comment]
Have you disabled the included notification service in KDE plasma?

**Comment by intrnl** [comment]
notifications service shouldn't be the issue

**Comment by intrnl** [comment]
@alx365 you should probably try to give us some logs..?

**Comment by alx365** [comment]
The issue seems to be revolved after i reinstalled
