### ISSUE TITLE
EnhancedDiscord no longer works on latest Discord version

### ISSUE THREAD

**Issue by trevnels** [joe27g/EnhancedDiscord#137]
As of Discord Stable 64675, EnhancedDiscord no longer functions properly. It does write a few normal initialization lines to the console:
```
[EnhancedDiscord] v2.8 is running. Validating plugins...
[EnhancedDiscord] Plugins validated.
```
However, there is no ED-related output after this. Once Discord loads, CSS and plugins are not applied and there are no entries in the Discord settings. Neither reinjection of EnhancedDiscord (in stable or beta) nor reinstallation of Discord seems to fix this.

**Comment by BowDown097** [comment]
yep, happens to me too

**Comment by user54232** [comment]
Same issue here.
No output at at all for me, used LinuxED to install on Arch.
Seems like Discord is ignoring ED completely in my case. 
Pasting full output below:
`Discord 0.0.11
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/---/.config/discord/0.0.11/modules
[Modules] Module installed file path: /home/---/.config/discord/0.0.11/modules/installed.json
[Modules] Module download path: /home/---/.config/discord/0.0.11/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
[Modules] Starting to install discord_krisp...
[Modules] Fetching discord_krisp@0 from https://discord.com/api/modules/stable/discord_krisp/0
[Modules] Streaming discord_krisp@0 to /home/---/.config/discord/0.0.11/modules/pending/discord_krisp-0.zip
Error downloading with electron net: HTTP Error: Status Code 403
Falling back to node net library..
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
[Modules] Failed fetching module discord_krisp@0: Error: HTTP Error: Status Code 403
[Modules] Finished module downloads. [success: 0] [failure: 1]`

**Comment by eslym** [comment]
I found out the dom_shit.js wait forever for window.webpackJsonp

**Comment by rauenzi** [comment]
That's not quite the case. The issue happens on the next line where it is trying to assign something to the ED global var. However the ED global var is undefined due to context isolation. See PR #138

**Comment by trevnels** [comment]
Still not fixed for me. Even after installing the hotfixed version the same behavior occurs. I have a completely standard discord installation apart from ED.

**Comment by trevnels** [comment]
Alright, I think I found a different bug in the installer. Injecting without overwriting the existing folder doesn't actually inject. Everything works now.
