### ISSUE TITLE
Doesn't work with the latest version of discord, in Linux.

### ISSUE THREAD

**Issue by ItsNeverLand** [joe27g/EnhancedDiscord#139]

**Comment by rauenzi** [comment]
Can you provide additional information? Versions you're using? Using latest ED? Logs?

**Comment by ItsNeverLand** [comment]
Latest Linux version of discord, and the latest version (as I wrote that
issue) of ED

**Comment by joe27g** [comment]
What exactly doesn't work? Does it fail to install or are any plugins loading? Are there errors or messages about ED in the console? (ctrl+shift+i)
Issues need to be as specific as possible; if we don't know what the problem is, there's no possibility of fixing it.

**Comment by ItsNeverLand** [comment]
It doesn't load.

Joe <notifications@github.com> escreveu no dia domingo, 9/08/2020 à(s)
18:46:

**Comment by rauenzi** [comment]
Without logs, a proper description, or even actual version numbers, there's not much we can do.

**Comment by ItsNeverLand** [comment]
Right now, I can't give logs, since it was on my mother's computer. Give me a week, I'll test it again, and if it still doesn't work, I'll send the logs, the version and everything.

**Peace**
_NeverLand.
Skript Developer._

**Comment by HarmoGlace** [comment]
Okay `Script developer`

**Comment by ItsNeverLand** [comment]
It's called skript.

**Comment by ItsNeverLand** [comment]
Hey there. After further investigation, it's provably because I'm running this on Linux.

Thanks anyways.

NeverLand
_**SKRIPT DEVELOPER**_

(It's Called Skript.)

**Comment by rauenzi** [comment]
I fail to see what relevance being a/the "Skript Developer" has to this issue.

**Comment by ItsNeverLand** [comment]
OK just pretend I said nothing lol
