### ISSUE TITLE
Grammarly support

### ISSUE THREAD

**Issue by ThatLifeofGames** [joe27g/EnhancedDiscord#14]
So uh, spell checker is pretty good but grammarly is better, is it possible to replace it?

Might be quite complicated but a really cool feature.

**Comment by jakuski** [comment]
Grammarly is not open source nor does it have a public API so this is **most likely** not possible.

**Comment by joe27g** [comment]
Well, obviously it's been a while since anyone mentioned this, so... Doesn't look like it's going to happen. If someone sees this and thinks they have more info about how to accomplish this, please make an issue on the [plugins repo](https://github.com/joe27g/EnhancedDiscord-Plugins).
