### ISSUE TITLE
Can't watch streams on Linux

### ISSUE THREAD

**Issue by katacarbix** [joe27g/EnhancedDiscord#141]
**Steps to reproduce**
1. Enter a voice channel when one or more people are streaming
2. Pop out the player in a new window
3. Click one of the stream thumbnails
4. It shows the loading animation indefinitely
5. Closing the window or ending the call will cause Discord to crash

This does not happen and streams are watchable when the player is still inside the main window.
This does not happen when ED is not injected.
This still happens with all plugins disabled.

**Desktop info**
OS: Ubuntu 20.04.1
Window manager: i3
ED: master (`71f79a0`)
Discord version:
> Stable 65705 (d72a93f)
> Host 0.0.11
> Linux 64-Bit (5.4.0-42-Generic)

**Comment by rauenzi** [comment]
@joe27g may want to do something like this https://github.com/rauenzi/BetterDiscordApp/commit/521056b7ef5cb073433dbe1d0caec9d8aaafb4ca
