### ISSUE TITLE
Please allow us to enable win32 themes

### ISSUE THREAD

**Issue by Shadowblitz16** [joe27g/EnhancedDiscord#142]
please allow us to disable css themes and use the default win32 themes
I want to be able to use a 95 theme with my os

**Comment by rauenzi** [comment]
You can just delete the CSS file or open the file and delete the contents. Or even disable the css loader if I recall correctly.

**Comment by joe27g** [comment]
Not sure what this is supposed to mean, but I assume you're talking about enabling the default windows title bar instead of the styled one. That's outside the scope of this project; you can probably dig around a bit with a search engine and find a way to do it.

**Comment by Shadowblitz16** [comment]
@joe27g 
I mean all the control looking like win32 controls
