### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Boii1** [joe27g/EnhancedDiscord#145]
Could someone provide a copy of theme.css?

**Comment by Boii1** [comment]
It's the SSL ticket.

**Comment by joe27g** [comment]
Fixed the certificate issues. For reference, the theme isn't actually stored on the webserver; it's just a mirror of https://raw.githubusercontent.com/joe27g/Discord-Theme/master/theme.css with a proper `content-type` header, so if the site's down you can download it there.

**Comment by Boii1** [comment]
Ty I will keep that in mind.
