### ISSUE TITLE
BetterDiscord plug-ins not working due to recent changes

### ISSUE THREAD

**Issue by bakzkndd** [joe27g/EnhancedDiscord#146]
BDFDB switched from remote to local as of recently due to security concerns. This has broken some of the betterdiscord plug-ins.

Example:
![image](https://user-images.githubusercontent.com/50497725/93690597-7c184000-fada-11ea-801c-d0ce29bd52d4.png)

On BetterDiscord it would show the following:
![image](https://user-images.githubusercontent.com/50497725/93690622-c4376280-fada-11ea-9109-04274c8edc32.png)
But this doesn't work on EnhancedDiscord

**Comment by MasicoreLord** [comment]
Not surprising, as a lot of plugins look in only specific locations for some stuff, that'd only be true if you were on BandagedBD.

For now I suggest, re-downloading all the DevilBro plugins you were using, and fetch his local library plugin, and place them all in your plugins folder.  Afterwards quit out of Discord and re-open it.
You should then be able to use their plugins again.

**Comment by MasicoreLord** [comment]
Be sure you either delete or overwrite the old versions of his plugins, otherwise you'll get that alert again.

**Comment by MasicoreLord** [comment]
If that doesn't work, make sure ED is updated, failing that, if you are having issues using/loading BBD plugins, report the bug if it hasn't already so contributors and collaborators are aware, and might fix it.

**Comment by alsoGAMER** [comment]
> Be sure you either delete or overwrite the old versions of his plugins, otherwise you'll get that alert again.

I've just done this, and now all the BD plugins are working again.

**Comment by MasicoreLord** [comment]
@joe27g This issue can be closed, as the problem they described, not only did it have nothing to do w/ the title, but the issue it actually was, is resolved.

**Comment by userXinos** [comment]
- ED updated, plugin updated 
- BD plugins is enabled
- only one BD plugin is included besides the standard plugins
- plugin works in BD

![img](https://user-images.githubusercontent.com/40886699/94244623-5a3c1480-ff43-11ea-83dc-49ffc00ed3f4.png)

**Comment by MasicoreLord** [comment]
Update ED, looks to be caused by an issue that was fixed yesterday, @userXinos

**Comment by MasicoreLord** [comment]
Make sure to restart Discord after updating, not reloading w/ something like CTRL + R
