### ISSUE TITLE
Server Full format emote

### ISSUE THREAD

**Issue by agent31750** [joe27g/EnhancedDiscord#15]
A plugin that show all available emotes of the server in the full format like `<a:yeet:416559878291718144>`

**Comment by rauenzi** [comment]
Looks like a good plugin to me 👀

**Comment by joe27g** [comment]
Note to self: Combine this with "Hide Disabled Emojis" (~~steal~~ borrow from [this BD version](https://github.com/rauenzi/BetterDiscordAddons/blob/master/Plugins/HideDisabledEmojis/HideDisabledEmojis.plugin.js)) and remove from theme

**Comment by jakuski** [comment]
[This is now a thing](https://github.com/jakuski/ed_plugins/tree/master/ServerEmojis)
