### ISSUE TITLE
Selective Presence

### ISSUE THREAD

**Issue by jakuski** [joe27g/EnhancedDiscord#16]
Don't even know if this is possible but a plugin which allows you to choose what app's RPC to go to your profile and block other apps from showing up.

**Comment by MayhemBill** [comment]
Just commenting to see what the status of this is?

**Comment by jakuski** [comment]
If anyone wants to actually do presence "filtering", the best way to do it would be preventing dispatch emitting the `ACTIVITY_UPDATE_START` event if `applicationId` is an unwanted one.

**Comment by joe27g** [comment]
This issue is a bit stale, so I'm going to close it for that reason, and because if someone still wants this, it should be suggested in the [plugins repo](https://github.com/joe27g/EnhancedDiscord-Plugins).
