### ISSUE TITLE
Discord 0.0.309 will immediately crashed after pasting url

### ISSUE THREAD

**Issue by eslym** [joe27g/EnhancedDiscord#160]
the latest discord (0.0.309) with EnhancedDiscord will crash immediately after pasting url

I can't find the log file for this but here is the diagnostic i tried:
1. remove enhanced discord: works fine
2. disable all plugins: crashed

now i am using the old version (0.0.308) without updating discord

**Comment by conpatto** [comment]
Download the beta branch, or opt into beta on the installer

**Comment by eslym** [comment]
> 
> 
> Download the beta branch, or opt into beta on the installer

it works, thanks
