### ISSUE TITLE
Autocorrect

### ISSUE THREAD

**Issue by ThatLifeofGames** [joe27g/EnhancedDiscord#17]
Discord has regular spell check, but why not autocorrect?

_Suggested by Maxbeebs, not me._ 
![image](https://user-images.githubusercontent.com/35865509/39253823-ae5eaf3e-48a0-11e8-8bbf-243326842aae.png)

**Comment by Thatlifeofgames** [comment]
C'mon Joe still not labels added yet...

(Oh and at least github isnt blocked in my school) :joy:

**Comment by IceHacks** [comment]
Enable BD plugins in settings and get this plugin https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/AutoCorrect.plugin.js should work ;)

**Comment by joe27g** [comment]
Accepting the above comment as a solution, since I don't see this being added as an ED plugin anytime soon.
