### ISSUE TITLE
screenshare

### ISSUE THREAD

**Issue by duxepw** [joe27g/EnhancedDiscord#20]
screenshare doesnt work when using ED

**Comment by Thatlifeofgames** [comment]
Can you test this without ED installed? It might be a discord issue.

**Comment by duxepw** [comment]
i tested it with my friend. with ED installer screenshare doesnt work for both of us and we can see others screenshare he uninstalled ED i couldnt see his screenshare and he could see mine

**Comment by Thatlifeofgames** [comment]
Yeah sorry, just found out that it was just ED that's why I removed my comment.

**Comment by duxepw** [comment]
np imma try to find what did dis

**Comment by duxepw** [comment]
even with no plugins it doesnt work so its something deep in the code xd

**Comment by Thatlifeofgames** [comment]
Are you using the beta or master?

**Comment by Thatlifeofgames** [comment]
Also, probably easier to talk in the support server https://discord.gg/jWVp5jR
