### ISSUE TITLE
Settings tabs don't always "unclick" properly

### ISSUE THREAD

**Issue by joe27g** [joe27g/EnhancedDiscord#4]
Sometimes clicking off the ED settings tabs won't mark them as deselected.
![image](https://user-images.githubusercontent.com/20873239/37161228-b88dea56-22b7-11e8-9a4f-87f7dea23da2.png)

**Comment by jakuski** [comment]
To add to this, trying to navigate to `My Account` from an ED setting tab will result in the element being console.log'd and not actually navigating.
