### ISSUE TITLE
ED Crashing when clicking on settings icon

### ISSUE THREAD

**Issue by CHIEFDAC** [joe27g/EnhancedDiscord#44]
Just recently downloaded this and am loving the new skin on Discord. Wanted to still be able to use my settings button on the screen though.

Every time I click it with ED on, it crashes my Discord.

Edit: Everything else works just fine on it

**Comment by CHIEFDAC** [comment]
![image](https://user-images.githubusercontent.com/8178130/47253582-fccbee80-d422-11e8-84a8-7794a6ddeb3a.png)

**Comment by ThatLifeofGames** [comment]
Can confirm, here is the console error when you click it: 
<img width="281" alt="1540025760" src="https://user-images.githubusercontent.com/35865509/47253678-66152700-d44e-11e8-808e-24c62f29e836.png">
