### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by ThatLifeofGames** [joe27g/EnhancedDiscord#50]
It looks like ED is suffering from memory leaks, or normal discord itself.
It has nothing to do with BD plugin loading either, as it happens on both.

https://thatlifeofgames.com/img/1542569403.png (had to close with task manager as it totally crashed)
https://cdn.discordapp.com/attachments/415248292767727616/513798431266045963/unknown.png
https://cdn.discordapp.com/attachments/415248292767727616/513817209982943241/unknown.png
https://cdn.discordapp.com/attachments/415248292767727616/513817577839919124/unknown.png

**Comment by rauenzi** [comment]
This has happened to me as well on vanilla Discord. From our experience in v2 development it seems the user objects and message objects can be leaky with references held somewhere. So loading members and messages in larger servers can cause this.

**Comment by ThatLifeofGames** [comment]
Discords problem so I'm closing this. Hopefully been fixed in discord anyway.
