### ISSUE TITLE
Installer crashes Discord Client without error

### ISSUE THREAD

**Issue by qsie** [joe27g/EnhancedDiscord#55]
During installation, Discord Client closes (which I believed to be intentional), but instead the process had uncleanly terminated. 

Only error detected was in deletion of local files, where Windows username has space and program did not account for this (where name is John Doe, "Could not find C:\Users\John")

**Comment by agent31750** [comment]
I  suggest renaming your user folder following [this guide](https://www.tenforums.com/tutorials/89060-change-name-user-profile-folder-windows-10-a.html). Since some dependencies doesn't support special user folder name

**Comment by joe27g** [comment]
This is essentially the same issue as #92, just stated in a different way, so I'll go ahead and close this one.
