### ISSUE TITLE
Settings tab

### ISSUE THREAD

**Issue by Roki100** [joe27g/EnhancedDiscord#56]
Settings tab appears only when pressing experiments it appears but it works only in ed vanilla.
With installed bd and ed at once, ed and bd works but settings tab from ed is not appearing from any click on experiments
Please fix it so fast xd

**Comment by jakuski** [comment]
EnhancedDiscord and BetterDiscord are not designed to run side by side.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mdashl** [comment]
Having the same issue.
Not exactly Experiments, you need to select any tab, then ED settings appears

**Comment by ThatLifeofGames** [comment]
This is an issue, and has been for a while now. Try clicking the experiments tab first and the others should appear.

**Comment by IndyV** [comment]
This issue has been fixed in [the fork of Rauenzi](https://github.com/rauenzi/EnhancedDiscord/blob/master/plugins/ed_settings.js). The loader on the EnhancedDiscord site has not been updated.

**Comment by joe27g** [comment]
fixed in #47
