### ISSUE TITLE
Issue with installer

### ISSUE THREAD

**Issue by BrianVEA** [joe27g/EnhancedDiscord#61]
Good evening, I've been experiencing the following issues with the installer, I managed to install ED manually on the regular Discord version (still running in to some plugin issues) but I seem to be unable to resolve this issue with the installer, log gives the following error.

`[INFO][1:48:14 AM Thursday, February 14, 2019]: Starting...
[INFO][1:48:15 AM Thursday, February 14, 2019]: Using release discordcanary
[INFO][1:48:15 AM Thursday, February 14, 2019]: Injecting...
[INFO][1:48:16 AM Thursday, February 14, 2019]: Detected platform: Windows | Discord release: discordcanary
[ERROR][1:48:16 AM Thursday, February 14, 2019]: Could not fine injection file with basepath C:\Users\Brian-PC\AppData\Roaming
`

My roaming folder isn't in the default location as I have moved this in the past to a larger SSD, which appears to be causing this issue.

**Comment by joe27g** [comment]
> My roaming folder isn't in the default location

Since this is kind of an edge case, I'm going to close this on the note that our new installer (don't ask for an ETA :P) will have an option for a custom installation path.
