### ISSUE TITLE
Depreciated CSS

### ISSUE THREAD

**Issue by explasion** [joe27g/EnhancedDiscord#65]
In your CSS [https://github.com/joe27g/EnhancedDiscord/master/plugins/Style.css](url) use global instead of root; root is about to be depreciated, and not all users will know to fix this for their themes if not given a good example theme.

**Comment by Cr3atable** [comment]
Wrong repo, please move this to https://github.com/joe27g/Discord-Theme

**Comment by IndyV** [comment]
Could you also please elaborate?

I can't find anything about root being deprec~~i~~ated nor the use of global in CSS (only with CSS modules which don't seem to serve much purpose here)

**Comment by rauenzi** [comment]
Yeah root is not being deprecated (I assume this is the word you meant) and global isn't even official yet so this is inaccurate.
