### ISSUE TITLE
installer problems

### ISSUE THREAD

**Issue by joe27g** [joe27g/EnhancedDiscord#70]
ok, so several people have had problems with being unable to launch discord due to the injection path being wrong/ the file not existing. to ensure that these errors are non-destructive, some of the following should be done:
- download and extract the ED files BEFORE injecting
- check that the path exists before setting it as the injection file
- maybe add a note saying to uninject before deleting injection file

also, a note that's somewhat related: checking registry entry `Computer\HKEY_CLASSES_ROOT\Discord\shell\open\command` could make the installer better.

**Comment by YouKnowBlom** [comment]
Sounds good overall. I'd also like to add: having the ability to manually specify the path to index.js, just for edge cases

**Comment by tommyettinger** [comment]
I am having this injection path problem; is there a known solution?
