### ISSUE TITLE
Discord crashes when going into settings

### ISSUE THREAD

**Issue by Astrol99** [joe27g/EnhancedDiscord#71]
With multiple attempts of going into discord settings by reinjecting and reinstalling, it returns an error window then restarts discord. Logs show normal operations

![Capture](https://user-images.githubusercontent.com/41875791/56626750-a2e1f680-6608-11e9-9cdb-3b7c59fb25b3.JPG)

**Comment by hamsterofficial** [comment]
Don't use for now Canary/PTB version , because findModule('itemSelected') doesn't exist in these versions.

**Comment by timmysgithub** [comment]
I'm confirming this issue, using the most recent stable official version of discord.

**Comment by Xenorio** [comment]
Confirming this too.

Discord build: 36215
OS: Pop!_OS 19.04

If you want to go into the settings right now, just remove the ed_settings plugin. You won't have the EnhancedDiscord settings tho.
