### ISSUE TITLE
The installer in the repo is not up to date

### ISSUE THREAD

**Issue by Cr3atable** [joe27g/EnhancedDiscord#73]
The installer in the releases tab of this repo is not up to date, meaning anyone who gets it from the repo will have a broken installation. An up to date version can be found [here](https://enhanceddiscord.com/EnhancedDiscord.exe).

**Comment by joe27g** [comment]
Lazy fix implemented. https://github.com/joe27g/EnhancedDiscord/releases/tag/2.3.1
