### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by JillCrungus** [joe27g/EnhancedDiscord#77]
This began happening with the Discord update that added server boosting. Attempting to launch Discord Canary (Untested on other builds) with ED enabled results in this error:
![image](https://user-images.githubusercontent.com/32760843/59139321-4d7c6180-898a-11e9-81f6-d790e8fa1bb7.png)

**Comment by PixeLInc** [comment]
Try updating your client - I had this issue happen to me with the update but since then there's been a new update that seems to have fixed it.

All good on my end with Discord Canary v0.0.81

**Comment by JillCrungus** [comment]
> Try updating your client - I had this issue happen to me with the update but since then there's been a new update that seems to have fixed it.
> 
> All good on my end with Discord Canary v0.0.81

This seems to be right, it's fixed in latest Canary versions.

**Comment by JillCrungus** [comment]
This issue seems to have come back on the latest Canary.

**Comment by rauenzi** [comment]
Can you try replacing your `injection.js` in the `EnhancedDiscord` folder with the one found here? https://raw.githubusercontent.com/joe27g/EnhancedDiscord/41147423122f39ddc74cb7dd456b600f6ba4722d/injection.js

Then fully close and reopen discord

**Comment by JillCrungus** [comment]
> Can you try replacing your `injection.js` in the `EnhancedDiscord` folder with the one found here? https://raw.githubusercontent.com/joe27g/EnhancedDiscord/41147423122f39ddc74cb7dd456b600f6ba4722d/injection.js
> 
> Then fully close and reopen discord

Yep, that did the trick.
