### ISSUE TITLE
Using findModule and others

### ISSUE THREAD

**Issue by InitialCosmo** [joe27g/EnhancedDiscord#87]
I apologize if this is the wrong place to ask this but I didn't know where else.

I'm wondering how to figure out what modules to use "findModule/findModuleByDisplayName" for.
I can pick some stuff out via React Dev-Tools, but I can't figure out where you'd find modules such as "sendMessage" and "getMentionCount" and how you can find those and use them?

Another thing I've been struggling with is accessing values on the TextArea object, 
Let's say I want to grab the TextArea `findModuleByDisplayName("ChannelTextArea")` and then, set the content for a script? 
I cannot access the .value prop of it so I guess due to my lack of understanding on this, how would that be achieved.
I can set it by grabbing the textArea using js and manually doing .value but the textbox fails to realize that the textbox has been updated.

Again, my apologies if this isn't correct or I'm just not seeing something.
Thanks!

**Comment by joe27g** [comment]
This sounds like something that should be discussed in our Discord server. As for the first part, you can find those (and most) modules just like this: `findModule("sendMessage")` and use them like this: `findModule("sendMessage").sendMessage(channelID, messageObj)`.

As for everything else, I recommend going to our support server (see the main page for the repo.)
