### ISSUE TITLE
Avatar Links plugin doesn't work

### ISSUE THREAD

**Issue by sidnoway** [joe27g/EnhancedDiscord#91]
Neither "Avatar Links" nor "Double-Click Edit" don't work, which is strange because they ship with ED.

**Comment by jakuski** [comment]
Hey there,

Discord recently pushed out an update that broke alot of plugins. You'll just have to wait until a fix for these is made.

As for the second part of your issue, please note that EnhancedDiscord and its bundled plugins are shipped without warranty of any kind. More info can be found in the license file. :grinning:

**Comment by joe27g** [comment]
As of 6ddf878, double-click edit works again. Avatar links is still broken for now, so I'm going to change the title of this issue.
