### ISSUE TITLE
Installer does not accept spaces in usernames

### ISSUE THREAD

**Issue by torksrevol** [joe27g/EnhancedDiscord#92]
Hello,

The path of install doesn't read the spaces in the username, can fix it?

Like  "User Name" > installer read to "User " and no more

**Comment by ThatLifeofGames** [comment]
The only thing you can do right now is do the advanced installation [here](https://github.com/joe27g/EnhancedDiscord/blob/master/advanced_installation.md)

There's no (known) workaround to get it working in the installer.

Also best off joining the support server for further help.

**Comment by joe27g** [comment]
As mentioned in #55, this may cause the client to crash as well.
