### ISSUE TITLE
Unhandled Exception on install

### ISSUE THREAD

**Issue by sidnoway** [joe27g/EnhancedDiscord#99]
![Untitled](https://user-images.githubusercontent.com/42903512/69446708-0230f200-0d23-11ea-91ae-a9db241c2344.png)

This pops up when I try to install EnhancedDiscord.
My computer is running Windows 7 x64, and my Discord install is completely vanilla.

No clue how to fix this. :/

**Comment by Awaydays** [comment]
Try updating .net from here: https://dotnet.microsoft.com/download/dotnet-framework-runtime
If that doesn't work make sure you don't have any Windows updates pending.

**Comment by sidnoway** [comment]
I do have updates pending! I will install those and report back if I still have problems.

**Comment by sidnoway** [comment]
Needed to install updates. That's it.
